apiVersion: v1
kind: Service
metadata:
  name: red-client
  labels:
    app: red-client
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31221
  selector:
    app: red-client
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: red-client
  labels:
    app: red-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: red-client
  template:
    metadata:
      labels:
        app: red-client
    spec:
      containers:
      - name: red-client
        image: IMAGE_TAG_HERE
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 0.02
            memory: 32Mi
        env:
        - name: ACTIVE_PROFILE
          valueFrom:
            configMapKeyRef:
              name: const-config
              key: active-profile
        - name: EXTRA_CONFIG
          value: '{}'
        - name: WORKER_IP
          valueFrom:
            configMapKeyRef:
              name: const-config
              key: worker-ip
